### ISSUE TITLE
Rename repo to Open Data Day 2015

### ISSUE THREAD

**Issue by trevortwining** [NiagaraOpenData/opendata#1]
I wanted to post here to get some consensus around the issue instead of arbitrarily changing it. I just know that someone might get the wrong idea if they see this repo name. They don't know we're doing this in a tongue-in-cheek sort of way.

**Comment by trevortwining** [comment]
tagging @adam12 @controlz @knicklabs

**Comment by mmottola24** [comment]
I completely agree and wanted to change it but didn't for the same reason you didn't.

Maybe just `Open Data 2015` since we could continue to publish stuff leading up to the conference in May.

**Comment by adam12** [comment]
Could just be something simple like `opendata`

I don't think we need to segment it by date - some of that information will be relevant for years to come, I think.

**Comment by mmottola24** [comment]
> Could just be something simple like opendata

:+1:

**Comment by knicklabs** [comment]
+1 for removing 2015 from the repo name. The date is not relevant.

**Comment by trevortwining** [comment]
Done.
